services:
  - type: web
    name: sentinel-api
    env: docker
    plan: free
    startCommand: java -jar /deployments/quarkus-run.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false 